package com.vibeops.heal;

import com.vibeops.mcp.McpProtocol;
import com.vibeops.mcp.McpTool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * MCP Tool: diagnose-failure
 * Analyzes error logs or live pod/container status to diagnose failures.
 * Returns a structured report with error classification and repair suggestions.
 */
@Component
public class DiagnoseFailureTool implements McpTool {

    private static final Logger log = LoggerFactory.getLogger(DiagnoseFailureTool.class);

    private final ErrorAnalyzer analyzer;
    private final HealingStrategyEngine strategyEngine;

    public DiagnoseFailureTool(ErrorAnalyzer analyzer, HealingStrategyEngine strategyEngine) {
        this.analyzer = analyzer;
        this.strategyEngine = strategyEngine;
    }

    @Override
    public String name() {
        return "diagnose-failure";
    }

    @Override
    public String description() {
        return "Analyzes error logs, stack traces, or deployment failure output to diagnose the root cause. " +
               "Classifies errors into categories (OOM, connectivity, config, code bugs, etc.) and " +
               "returns a structured diagnosis with severity, repair suggestions, and actionable commands.";
    }

    @Override
    public McpProtocol.InputSchema inputSchema() {
        return new McpProtocol.InputSchema(
                "object",
                Map.of(
                        "logs", new McpProtocol.PropertyDef("string",
                                "Error logs, stack traces, or kubectl/docker output to analyze", null),
                        "context", new McpProtocol.PropertyDef("string",
                                "Optional context about the deployment (e.g., service name, environment)", null)
                ),
                List.of("logs")
        );
    }

    @Override
    public McpProtocol.ToolResult execute(Map<String, Object> arguments) {
        String logs = (String) arguments.get("logs");
        String context = (String) arguments.getOrDefault("context", "");

        if (logs == null || logs.isBlank()) {
            return McpProtocol.ToolResult.error("Parameter 'logs' is required.");
        }

        // Analyze error patterns
        ErrorAnalyzer.AnalysisResult analysis = analyzer.analyze(logs);

        // Generate repair plan
        HealingStrategyEngine.RepairPlan plan = strategyEngine.createRepairPlan(analysis);

        // Build report
        String report = generateDiagnosisReport(analysis, plan, context);
        return McpProtocol.ToolResult.success(report);
    }

    private String generateDiagnosisReport(ErrorAnalyzer.AnalysisResult analysis,
                                            HealingStrategyEngine.RepairPlan plan,
                                            String context) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Failure Diagnosis Report\n\n");

        if (analysis.errors().isEmpty()) {
            sb.append("## Result: No Known Error Patterns Detected\n\n");
            sb.append("The provided logs did not match any known error patterns.\n");
            sb.append("Consider providing more log context or checking manually.\n\n");

            if (!analysis.stackTraces().isEmpty()) {
                sb.append("However, **%d stack trace(s)** were found:\n\n".formatted(analysis.stackTraces().size()));
                for (String trace : analysis.stackTraces()) {
                    sb.append("```\n").append(truncate(trace, 800)).append("\n```\n\n");
                }
            }

            sb.append("---\n*Generated by Vibe-Ops Self-Healing Agent v0.1.0*\n");
            return sb.toString();
        }

        // Severity banner
        String severityLabel = switch (analysis.severity()) {
            case CRITICAL -> "CRITICAL — Immediate action required";
            case HIGH -> "HIGH — Action required";
            case MEDIUM -> "MEDIUM — Should be addressed";
            default -> "LOW";
        };
        sb.append("## Severity: %s\n\n".formatted(severityLabel));

        // Error breakdown
        sb.append("## Detected Errors (%d)\n\n".formatted(analysis.errors().size()));
        sb.append("| Error ID | Category | Description |\n");
        sb.append("|----------|----------|-------------|\n");
        for (ErrorAnalyzer.MatchedError error : analysis.errors()) {
            sb.append("| %s | %s | %s |\n".formatted(
                    error.pattern().id(),
                    error.pattern().category(),
                    error.pattern().description()));
        }
        sb.append("\n");

        // Detailed error context
        for (ErrorAnalyzer.MatchedError error : analysis.errors()) {
            sb.append("### %s — %s\n\n".formatted(error.pattern().id(), error.pattern().description()));
            sb.append("**Matched text**: `%s`\n\n".formatted(error.matchedText()));
            sb.append("**Context**:\n```\n%s\n```\n\n".formatted(error.context()));
        }

        // Repair plan
        sb.append("## Repair Plan\n\n");
        if (plan.requiresCodeChange()) {
            sb.append("This failure **requires code changes**. Recommended to invoke Claude Code for automated repair.\n\n");
        }
        if (plan.hasAutomatableActions()) {
            sb.append("Some actions can be **automated**. Use `auto-heal` tool for one-click repair.\n\n");
        }

        sb.append("| # | Action | Type | Auto |\n");
        sb.append("|---|--------|------|------|\n");
        int i = 1;
        for (HealingStrategyEngine.RepairAction action : plan.actions()) {
            sb.append("| %d | %s | %s | %s |\n".formatted(
                    i++, action.title(), action.type(), action.automatable() ? "Yes" : "Manual"));
        }
        sb.append("\n");

        // Detailed repair steps
        sb.append("## Repair Steps\n\n");
        i = 1;
        for (HealingStrategyEngine.RepairAction action : plan.actions()) {
            sb.append("### %d. %s\n\n".formatted(i++, action.title()));
            sb.append("%s\n\n".formatted(action.description()));
            sb.append("**Commands**:\n");
            for (String cmd : action.commands()) {
                sb.append("```\n%s\n```\n".formatted(cmd));
            }
            sb.append("\n");
        }

        // Stack traces
        if (!analysis.stackTraces().isEmpty()) {
            sb.append("## Stack Traces\n\n");
            for (String trace : analysis.stackTraces()) {
                sb.append("```\n").append(truncate(trace, 1000)).append("\n```\n\n");
            }
        }

        sb.append("---\n*Generated by Vibe-Ops Self-Healing Agent v0.1.0*\n");
        return sb.toString();
    }

    private String truncate(String s, int maxLen) {
        return s.length() <= maxLen ? s : s.substring(0, maxLen) + "\n... (truncated)";
    }
}
